# Generated by Django 5.1.7 on 2025-03-31 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=100)),
                ('api_token', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('aitvo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='lojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loja', models.CharField(max_length=100)),
                ('Endereco', models.CharField(max_length=100)),
                ('Bandeira', models.CharField(max_length=100)),
                ('client_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
            ],
        ),
    ]
