# Generated by Django 5.1.7 on 2025-04-20 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('api_token', models.CharField(editable=False, max_length=43, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='integration',
            fields=[
                ('id_venda_item', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('id_venda', models.CharField(max_length=100)),
                ('data_venda', models.DateField()),
                ('data_envio', models.DateField()),
                ('tipo_envio', models.CharField(max_length=100)),
                ('id_cliente', models.CharField(max_length=100)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('segmento', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=100)),
                ('regiao', models.CharField(max_length=100)),
                ('id_produto', models.CharField(max_length=200)),
                ('descricao_produto', models.CharField(max_length=500)),
                ('categoria_produto', models.CharField(max_length=200)),
                ('subcategoria_produto', models.CharField(max_length=200)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=2)),
                ('quantidade_vendida', models.DecimalField(decimal_places=2, max_digits=2)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=2)),
                ('margem', models.DecimalField(decimal_places=2, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
            ],
        ),
    ]
