# Generated by Django 5.1.7 on 2025-04-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_clientes_aitvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
