# Generated by Django 5.1.7 on 2025-04-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_integration_desconto_alter_integration_margem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='desconto',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='integration',
            name='margem',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='integration',
            name='quantidade_vendida',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='integration',
            name='valor_venda',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
