# Generated by Django 5.1.7 on 2025-04-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_clientes_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lojas',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='client_id',
        ),
    ]
