# Generated by Django 5.1.7 on 2025-04-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_client_id_lojas_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojas',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
