# Generated by Django 5.1.7 on 2025-04-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dim_cliente_dim_produto_dim_tempo_entrega_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fato_vendas',
            old_name='id_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='fato_vendas',
            old_name='id_data_entrega',
            new_name='data_entrega',
        ),
        migrations.RenameField(
            model_name='fato_vendas',
            old_name='id_data_venda',
            new_name='data_venda',
        ),
        migrations.RenameField(
            model_name='fato_vendas',
            old_name='id_produto',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='fato_vendas',
            old_name='id_tipo_entrega',
            new_name='tipo_entrega',
        ),
        migrations.RenameField(
            model_name='fato_vendas',
            old_name='id_venda',
            new_name='venda',
        ),
    ]
