# Generated by Django 5.1.7 on 2025-04-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_dim_cliente_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='api_token',
            field=models.CharField(editable=False, max_length=43, unique=True),
        ),
    ]
